### ISSUE TITLE
2018年抽奖程序扰动范围-0.1 ~ +0.1不正确

### ISSUE THREAD

**Issue by JJaLing** [75team/raffle#1]
源码app.js第79行
 const subDuration = durations.map(d => d * factor * random(9, 11) / 10);
应该是
const subDuration = durations.map(d => d * factor * random(9, 2) / 10);
function random(m, n) {
  return m + Math.random() * n
}
这样才能保证误差在-0.1 - 0.1之间

**Comment by akira-cn** [comment]
是的，我改一下。。。
